name: Deploy Python app

on: 
  push: 
    branches: 
      - master

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Transfer files to server
      run: | 
        sshpass -p "${{ secrets.REMOTE_PASSWORD }}" scp -P 2415 -o StrictHostKeyChecking=no -r ./* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/vasiliy/practice_ci/
        
    - name: Run python script
      run: |
        sshpass -p "${{ secrets.REMOTE_PASSWORD }}" ssh -P 2415 -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd /home/vasiliy/practice_ci/ && python3 main.py"